sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7
    - os: linux
      dist: trusty
      env: LINT=1
      before_install:
        # In case we ever want to use a different version of clang-format:
        #- wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        #- echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list > /dev/null
        - sudo apt-get update -qq
        - sudo apt-get install -qq clang-format-3.8
      install: []
      script:
        - .travis/check-git-clang-format-output.sh

install:
  - bash build.sh
  - make
  - make test
  
